apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    # - image: udeshyagiri/cgpa-client
    #   context: client
    #   docker:
    #     dockerfile: Dockerfile.dev
    #   sync:
    #     '**/*.js': .
    #     '**/*.css': .
    #     '**/*.html': .
    - image: udeshyagiri/cgpa-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
deploy:
  kubectl:
    manifests:
      # - k8s/client-deployment.yaml
      # - k8s/client-cluster-ip-service.yaml
      - k8s/server-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
